/*
 Navicat MySQL Data Transfer

 Source Server         : zhushou2.0
 Source Server Type    : MySQL
 Source Server Version : 50733
 Source Host           : 10.187.13.5:3306
 Source Schema         : cpic_qytd

 Target Server Type    : MySQL
 Target Server Version : 50733
 File Encoding         : 65001

 Date: 05/03/2021 14:14:43
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for lp_coinsurance_spreadback
-- ----------------------------
DROP TABLE IF EXISTS `lp_coinsurance_spreadback`;
CREATE TABLE `lp_coinsurance_spreadback`  (
  `ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'ID',
  `DATA_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `REVISION` int(11) NULL DEFAULT NULL COMMENT '乐观锁',
  `DATA_DATE` datetime(0) NULL DEFAULT NULL COMMENT '统计时间',
  `REPORT_TYPE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '报表类型',
  `TOBEPAID_SERIALNUMBER` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '待付款流水号',
  `COMPANY_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分公司名称',
  `POLICY_NO` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '保单号',
  `LOT_NUMBER` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '批单号',
  `CLAIM_CODE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '赔案号',
  `CASE_CODE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '报案号',
  `UNIFIED_INSURANCE_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '统保代码',
  `DANGER_TIME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '出险时间',
  `CLAIM_TIME` datetime(0) NULL DEFAULT NULL COMMENT '核赔时间',
  `POLICY_HOLDER_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '投保人名称',
  `RECEIVABLE_APPORTIONMENT_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '应收摊赔金额',
  `WRITEOFF_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '核销金额',
  `WRITEOFF_STATE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '核销状态',
  `BUSINESS_TYPE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '类型',
  `TRACK_COMPANY_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '跟单公司名称',
  `APPORTIONMENT_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '摊赔编号',
  `CURRENCY` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '币种',
  `COMPANY_DIRECTION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '司内司外标志',
  `ASSURED` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '被保险人',
  `OPERATOR_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '经办人代码',
  `OPERATOR` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '经办人',
  `PROXY_POINT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '代理点',
  `CUSTOMER_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '客户名称',
  `CONTACT_UNIT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '联系单位',
  `REMARKS` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '备注',
  `P09_ACCESS` datetime(0) NULL DEFAULT NULL COMMENT 'P09接入日',
  `ACCOUNT_AGE_DAY` int(11) NULL DEFAULT NULL COMMENT '账龄天',
  `ACCOUNT_AGE_MONTH` int(11) NULL DEFAULT NULL COMMENT '账龄月',
  `DEPARTMENT_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '部门名称',
  `DUTY_DEPARTMENT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任部门',
  `DUTY_HANDLER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任人',
  `INSURANCE_KIND_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '险种代码',
  `INSURANCE_KIND_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '险种名称',
  `INSURANCE_KIND_TYPE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '险种大类',
  `CLOSE_TIME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '结案时间',
  `CONTACTS` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '联系人',
  `ADDRESS` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '地址',
  `TELEPHONE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '电话',
  `MAIL` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '邮箱',
  `PERFECT_STATE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '完善状态',
  `ACK_STATUS` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '确认状态',
  `START_PLAN_SPREADTIME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '最初预计摊回日',
  `PLAN_SPREADTIME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '预计摊回日',
  `PLAN_SPREADTIME_ADJUST` int(11) NULL DEFAULT NULL COMMENT '预计摊回日调整次数',
  `NOTICE_CREATE_TIME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '通知书生成日期',
  `WITH_POLICY_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '跟单方金额',
  `DATA_CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `CONVERT_RMB_BALANCE` decimal(32, 8) NULL DEFAULT NULL COMMENT '折人民币余额',
  `EXCHANGE_RATE` decimal(4, 2) NULL DEFAULT NULL COMMENT '汇率',
  `UNIFIED_INSURANCE_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '统保名称',
  `FINANCE_ORGANIZATION` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '财务机构',
  `POLICY_MANAGEMENT_TAG` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '保单管理标签',
  `NOT_RECOVERED_REASON` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '未摊回原因',
  `DATA_SOURCE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据源',
  `LIQUIDATE_PROCESS_NODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '清收过程节点',
  `TOTAL` decimal(32, 8) NULL DEFAULT NULL COMMENT '总额',
  `SHARE_PAYABLE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '应摊份额',
  `SHARE_PAYABLE_NEW` decimal(12, 8) NULL DEFAULT NULL COMMENT '应摊份额百分比',
  `CLAIM_DETAIL_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '赔案明细类型',
  `CLAIM_WRITEOFF_TIME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '赔案核销时间',
  `DATA_TIME_STAMP` datetime(0) NULL DEFAULT NULL COMMENT '时间戳',
  `CREATED_BY` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '共保摊回问题清单' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
