/*
 Navicat MySQL Data Transfer

 Source Server         : zhushou2.0
 Source Server Type    : MySQL
 Source Server Version : 50733
 Source Host           : 10.187.13.5:3306
 Source Schema         : cpic_qytd

 Target Server Type    : MySQL
 Target Server Version : 50733
 File Encoding         : 65001

 Date: 05/03/2021 14:13:19
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for lp_ml_sasssb_stockrecovery
-- ----------------------------
DROP TABLE IF EXISTS `lp_ml_sasssb_stockrecovery`;
CREATE TABLE `lp_ml_sasssb_stockrecovery`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID 主键',
  `REVISION` int(11) NULL DEFAULT NULL COMMENT '乐观锁',
  `DATA_DATE` datetime(0) NULL DEFAULT NULL COMMENT '统计时间',
  `COMPANY_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分公司代码',
  `COMPANY_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '分公司名称',
  `DEPARTMENT_GROUP_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '部门组代码',
  `DEPARTMENT_GROUP_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '部门组名称',
  `DEPARTMENT_CODE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '部门代码',
  `DEPARTMENT_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '部门名称',
  `CASE_CODE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '报案号',
  `CLAIM_CODE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '赔案号',
  `ADJUSTMENT_CODE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '理算书号',
  `ASSURED_NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '被保险人姓名',
  `DANGER_TIME` datetime(0) NULL DEFAULT NULL COMMENT '出险时间',
  `CASE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '报案时间',
  `ACCIDENT_LIABILITY` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '事故责任',
  `LIABILITY_PROPORTION` decimal(4, 2) NULL DEFAULT NULL COMMENT '责任比例',
  `CLAIM_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '核赔金额',
  `RECOURSE_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '应追偿金额',
  `RECOVERY_APPLY_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '追偿申请金额',
  `CLAIM_AGREE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '核赔通过时间',
  `CLAIM_PERSONNEL_CODE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '核赔人员代码',
  `CLAIM_PERSONNEL_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '核赔人员名称',
  `INSURANCE_KIND` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '险种',
  `RECOVERY_APPLY_TYPE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '追偿申请类型',
  `RECOVERY_APPLY_TIME` datetime(0) NULL DEFAULT NULL COMMENT '追偿申请时间',
  `RECOVERY_STATE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '案件追偿状态',
  `RECOVERY_APPLY_TASK` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '追偿申请任务',
  `TASK_HANDLER` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '任务处理人',
  `RECOVERY_TYPE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '系统触发追偿类型',
  `PLATFORM_SUBROGATION` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否平台代位',
  `RESPONSIBLE_PARTY_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任方名称',
  `RESPONSIBLE_PARTY_CTI_INSURANCE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任方交强险保险公司',
  `RESPONSIBLE_PARTY_CI_INSURANCE` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '责任方商业险保险公司',
  `RECOVERY_WAY` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '追偿方式',
  `RECOVERY_TRACK_OBJECT` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '追偿跟踪对象',
  `ADJUSTMENT_CLAIM_AGREE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '理算核赔通过时间',
  `RECOVERY_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '追偿金额',
  `SURPLUS_RECOVERY_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '剩余应追偿金额',
  `DATA_TIME_STAMP` datetime(0) NULL DEFAULT NULL COMMENT '时间戳',
  `RECOVERY_APPLY_NEW_MONEY` decimal(32, 8) NULL DEFAULT NULL COMMENT '最新追偿申请金额',
  `RECOVERY_REASON` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '应追偿原因',
  `IS_COMPLAINT` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否投诉',
  `DATA_TYPE` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据类型',
  `COOPERATE_LAWFIRM` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '合作律所',
  `SURVEYOR` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '查勘员',
  `REPAIR_SHOP` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '修理厂',
  `BUSINESS_TYPE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '类型',
  `CREATED_BY` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 91119 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '代位追偿问题清单 9家分公司' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
