/*
 Navicat MySQL Data Transfer

 Source Server         : zhushou2.0
 Source Server Type    : MySQL
 Source Server Version : 50733
 Source Host           : 10.187.13.5:3306
 Source Schema         : cpic_qytd

 Target Server Type    : MySQL
 Target Server Version : 50733
 File Encoding         : 65001

 Date: 05/03/2021 14:12:36
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for lp_subrogation_detail
-- ----------------------------
DROP TABLE IF EXISTS `lp_subrogation_detail`;
CREATE TABLE `lp_subrogation_detail`  (
  `ID` int(32) NOT NULL AUTO_INCREMENT COMMENT 'ID 主键',
  `DATA_DATE` date NULL DEFAULT NULL COMMENT '统计时间',
  `DATA_TIME_STAMP` datetime(0) NULL DEFAULT NULL COMMENT '时间戳',
  `REVISION` int(11) NULL DEFAULT NULL COMMENT '乐观锁',
  `COMPANY_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '分公司名称',
  `DEPARTMENT_GROUP_NAME` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '部门组名称',
  `DEPARTMENT_NAME` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '部门名称',
  `TARGETCAR_INDEMNITY` decimal(32, 2) NULL DEFAULT NULL COMMENT '标的车损赔款',
  `PLAN_RECOURSE_MONEY_PROPORTION` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '应追偿金额占标的车损赔款比',
  `PLAN_RECOURSE_NUMBER_CURRENT` int(11) NULL DEFAULT NULL COMMENT '应追偿数量(当期)',
  `PLAN_RECOURSE_NUMBER_ADD` int(11) NULL DEFAULT NULL COMMENT '应追偿数量(累计)',
  `PLAN_RECOURSE_MONEY_CURRENT` decimal(32, 2) NULL DEFAULT NULL COMMENT '应追偿金额(当期)',
  `PLAN_RECOURSE_MONEY_CURRENT_WD` decimal(32, 2) NULL DEFAULT NULL COMMENT '司内应追偿金额(当期)',
  `PLAN_RECOURSE_MONEY_ADD` decimal(32, 2) NULL DEFAULT NULL COMMENT '应追偿金额(累计)',
  `PLAN_INSURANCE` decimal(32, 2) NULL DEFAULT NULL COMMENT '有保险',
  `PLAN_INSURANCE_COMPANY` decimal(32, 2) NULL DEFAULT NULL COMMENT '无保险企业',
  `PLAN_INSURANCE_PERSON` decimal(32, 2) NULL DEFAULT NULL COMMENT '无保险自然人',
  `PLAN_RECOURSE_MONEY_CURRENT_WD_ADD` decimal(32, 2) NULL DEFAULT NULL COMMENT '司内应追偿金额(累计)',
  `RECOURSE_NUMBER_ACTUAL_CURRENT` int(11) NULL DEFAULT NULL COMMENT '实际追偿数量(当期)',
  `RECOURSE_NUMBER_ACTUAL_ADD` int(11) NULL DEFAULT NULL COMMENT '实际追偿数量(累计)',
  `RECOURSE_MONEY_CURRENT` decimal(32, 2) NULL DEFAULT NULL COMMENT '追偿金额(当期)',
  `RECOURSE_MONEY_CURRENT_WD` decimal(32, 2) NULL DEFAULT NULL COMMENT '司内追偿金额(当期)',
  `RECOURSE_MONEY_ADD` decimal(32, 2) NULL DEFAULT NULL COMMENT '追偿金额(累计)',
  `INSURANCE` decimal(32, 2) NULL DEFAULT NULL COMMENT '有保险',
  `INSURANCE_COMPANY` decimal(32, 2) NULL DEFAULT NULL COMMENT '无保险企业',
  `INSURANCE_PERSON` decimal(32, 2) NULL DEFAULT NULL COMMENT '无保险自然人',
  `RECOURSE_MONEY_CURRENT_WD_ADD` decimal(32, 2) NULL DEFAULT NULL COMMENT '司内追偿金额(累计)',
  `SUBROGATION_RECOVERYRATE_ADDWD` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '代位求偿追偿率 (累计)',
  `SUBROGATION_RECOVERYRATE_ADD` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '非司内代位求偿追偿率(累计)',
  `CLAIM_NUMBER_ACTUAL_ADD` int(11) NULL DEFAULT NULL COMMENT '当年核赔追偿数量(累计)',
  `CLAIM_MONEY_ACTUAL_ADD` decimal(32, 2) NULL DEFAULT NULL COMMENT '当年核赔追偿金额(累计)',
  `RECOVERYRATE_CURRENT_WD` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '当年追偿率',
  `RECOVERYRATE_CURRENT` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '非司内当年追偿率',
  `COST_RECOVERY` decimal(32, 2) NULL DEFAULT NULL COMMENT '费用追偿',
  `COST_RECOVERY_LEGAL` decimal(32, 2) NULL DEFAULT NULL COMMENT '追偿法律费用',
  `CREATED_BY` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9908 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci COMMENT = '代位追偿明细报表' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
